%YAML:1.0
# settings for file.version == "1.0"
File.version: "1.0"

#--------------------------------------------------------------------------------------------
# Camera Parameters. Adjust them!
#--------------------------------------------------------------------------------------------
Camera.type: "PinHole"

# left Camera calibration and distortion parameters (OpenCV) 
# 相机内参，相机坐标到像素坐标的变换
Camera1.fx: 320.0
Camera1.fy: 320.0
Camera1.cx: 320.0
Camera1.cy: 240.0

# 相机畸变参数
Camera1.k1: 0.0
Camera1.k2: 0.0
Camera1.p1: 0.0
Camera1.p2: 0.0

# Right Camera calibration and distortion parameters (OpenCV)
Camera2.fx: 320.0
Camera2.fy: 320.0
Camera2.cx: 320.0
Camera2.cy: 240.0

# distortion parameters
Camera2.k1: 0.0
Camera2.k2: 0.0
Camera2.p1: 0.0
Camera2.p2: 0.0

# transformation from right cemera to left camera
Stereo.T_c1_c2: !!opencv-matrix
    rows: 4
    cols: 4
    dt: f
    data: [1.0, 0.0, 0.0, 0.0,
          0.0, 1.0, 0.0, 0.1,
          0.0, 0.0, 1.0, 0.0,
          0.0, 0.0, 0.0, 1.0]

Camera.width: 640
Camera.height: 480

# Camera frames per second 
Camera.fps: 20

# stereo baseline times fx
# Camera.bf: 12.0
# Stereo.b: 0.1

# Color order of the images (0: BGR, 1: RGB. It is ignored if images are grayscale)
Camera.RGB: 1

# Close/Far threshold. Baseline times.
Stereo.ThDepth: 50.0

# IMU noise (Use those from VINS-mono)
IMU.NoiseGyro: 1.2341e-3 # 0.004 (VINS) # 0.00016 (TUM) # 0.00016    # rad/s^0.5 
IMU.NoiseAcc: 3.3285e-2 # 0.04 (VINS) # 0.0028 (TUM) # 0.0028     # m/s^1.5
IMU.GyroWalk: 7.0523e-8 # 0.000022 (VINS and TUM) rad/s^1.5
IMU.AccWalk: 8.826e-7 # 0.0004 (VINS) # 0.00086 # 0.00086    # m/s^2.5
IMU.Frequency: 200.0

# transformation from left camera to body-frame(imu)
IMU.T_b_c1: !!opencv-matrix
    rows: 4
    cols: 4
    dt: f
    data: [0.0, -0.3420201433256687, 0.9396926207859084, 0.35,
        1.0, 0.0, 0.0, -0.05,
        0.0, 0.9396926207859084, 0.3420201433256687, -0.1, 
        0.0, 0.0, 0.0, 1.0 ]

#--------------------------------------------------------------------------------------------
# ORB Parameters
#--------------------------------------------------------------------------------------------

# ORB Extractor: Number of features per image
ORBextractor.nFeatures: 1200

# ORB Extractor: Scale factor between levels in the scale pyramid 	
ORBextractor.scaleFactor: 1.2

# ORB Extractor: Number of levels in the scale pyramid	
ORBextractor.nLevels: 8

# ORB Extractor: Fast threshold
# Image is divided in a grid. At each cell FAST are extracted imposing a minimum response.
# Firstly we impose iniThFAST. If no corners are detected we impose a lower value minThFAST
# You can lower these values if your images have low contrast			
ORBextractor.iniThFAST: 20
ORBextractor.minThFAST: 7

#--------------------------------------------------------------------------------------------
# Viewer Parameters
#--------------------------------------------------------------------------------------------
Viewer.KeyFrameSize: 0.05
Viewer.KeyFrameLineWidth: 1.0
Viewer.GraphLineWidth: 0.9
Viewer.PointSize: 2.0
Viewer.CameraSize: 0.08
Viewer.CameraLineWidth: 3.0
Viewer.ViewpointX: 0.0
Viewer.ViewpointY: -0.7
Viewer.ViewpointZ: -1.8
Viewer.ViewpointF: 500.0

# loop closing: 0: not use; 1: use
loopClosing: 0

#------------------------------------
# save trajectory file path
#------------------------------------
PredictdTrajectory.filePath: "/mnt/d/uavs/vslam/results/mid/loop/max_v_5/orb_slam3/orbslam_noloop.txt"